# Improve colors
set -g default-terminal 'screen-256color'

# Act like vim
set -wg mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind | split-window -h
bind - split-window -v
bind -t vi-copy v begin-selection

# Copy to macOS clipboard
set -g default-command "reattach-to-user-namespace -l bash"

bind -t vi-copy y                 copy-pipe "reattach-to-user-namespace pbcopy"
bind -t vi-copy Enter             copy-pipe "reattach-to-user-namespace pbcopy"
bind -t vi-copy C-j               copy-pipe "reattach-to-user-namespace pbcopy"
bind -t vi-copy MouseDragEnd1Pane copy-pipe "reattach-to-user-namespace pbcopy"

bind ] run "reattach-to-user-namespace pbpaste | tmux load-buffer - && tmux paste-buffer"

# Rebind C-b to C-s
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Start window numbers at 1 to match keyboard order with tmux window order
set -g base-index 1
set -wg pane-base-index 1

# Renumber windows sequentially after closing any of them
set -g renumber-windows on

# Increase scrollback lines
set -g history-limit 10000

# Don't wait for the escape key to take effect
set -sg escape-time 0

# Increase the key repeat time to 1 second
set -g repeat-time 1000

# Increase the display-panes timeout to 3 seconds
set -g display-panes-time 3000

# Reload tmux configuration file
bind r source-file ${HOME}/.tmux.conf \; display-message "~/.tmux.conf reloaded"
